main:
    databasepath: file:data/telemetry.db?_foreign_keys=on&cache=shared&mode=rwc&_busy_timeout=1000

udb:
    udbdatabasepath: file:data/DMLiveObjectDatabase.db?cache=shared&_foreign_keys=off&mode=ro&_busy_timeout=1000
    shmdatabasepath: file:data/SHM.db?cache=shared&_foreign_keys=off&mode=ro&_busy_timeout=1000
    udbnotifypipe: data/udbnotify.pipe 
    startup: ["startup-events", "addon-events"]

pprof: [ "unix:data/http.socket" ]
SSE: [ "http::8080" ]
Redfish: [ "unix:data/http.socket" ]
pipe: [ "metric-engine.pipe" ]

triggers:
  clientIPCPipe: data/clientipc
  subList: data/sublist.json

Addon-Events:
  # this is to test the report definition update codepath
  - name: UpdateMetricReportDefinition
    data: |
      {
        "Name": "Thermal",
        "Enabled": true,
        "Type": "Periodic",
        "Period": 60,
        "Updates": "NewReport",
        "SuppressDups": true,
        "Actions": ["RedfishEvent", "LogToMetricReportsCollection"],
        "Metrics": [
          {"MetricID": "TemperatureReading"},
          {"MetricID": "RPMReading"}
         ]
       }


  # Test the update sad path
  - name: UpdateMetricReportDefinition
    data: |
      {
        "Name": "nonexistent",
        "Enabled": true,
        "Type": "Periodic",
        "Period": 60,
        "Updates": "NewReport",
        "SuppressDups": true,
        "Actions": ["RedfishEvent", "LogToMetricReportsCollection"],
        "Metrics": [
          {"MetricID": "TemperatureReading"},
          {"MetricID": "RPMReading"}
         ]
       }

  # this one is added as Disabled to ensure that disabled report processing is good. We can enable it later.
  - name: AddMetricReportDefinition
    data: |
      {
        "Name": "SMARTData",
        "Enabled": false,
        "Type": "Periodic",
        "Period": 3600,
        "Updates": "NewReport",
        "SuppressDups": false,
        "Actions": ["RedfishEvent", "LogToMetricReportsCollection"],
        "Metrics": [
          { "FQDDPattern": "SMARTData:%" }
        ]
      }

  - name: AddMetricReportDefinition
    data: |
      {
        "Name": "UBER-PER-WRAP",
        "Enabled": true,
        "Type": "Periodic",
        "Period": 60,
        "TimeSpan": 180,
        "Updates": "AppendWrapsWhenFull",
        "SuppressDups": true,
        "Actions": ["RedfishEvent", "LogToMetricReportsCollection"],
        "Metrics": [ {"MetricID": "%"} ]
       }

  - name: AddMetricReportDefinition
    data: |
      {
        "Name": "UBER-ONREQ",
        "Enabled": true,
        "Type": "OnRequest",
        "Period": 0,
        "TimeSpan": 60,
        "Updates": "AppendWrapsWhenFull",
        "SuppressDups": true,
        "Actions": ["RedfishEvent", "LogToMetricReportsCollection"],
        "Metrics": [ {"MetricID": "%"} ]
       }

  - name: AddMetricReportDefinition
    data: |
      {
        "Name": "UBER-ONCHG",
        "Enabled": true,
        "Type": "OnChange",
        "Period": 0,
        "TimeSpan": 60,
        "Updates": "AppendWrapsWhenFull",
        "SuppressDups": true,
        "Actions": ["RedfishEvent", "LogToMetricReportsCollection"],
        "Metrics": [ {"MetricID": "%"} ]
       }
